import { BiMap } from "react-icons/bi";

export const TAB_ITEM = [
  {
    label: "all",
    icon: <BiMap />,
    name: "전체보기",
  },
  {
    label: "pc",
    icon: "icon2",
    name: "PC",
  },
  {
    label: "mobile",
    icon: "icon3",
    name: "MOBILE",
  },
  {
    label: "responsive",
    icon: "icon4",
    name: "Responsive",
  },
];

export const CARD_ITEM = [
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title1",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "mobile",
    img: "http://placeimg.com/242/242/animals",
    title: "title2",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "responsive",
    img: "http://placeimg.com/242/242/animals",
    title: "title3",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title4",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title5",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title5",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title5",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title5",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title5",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title5",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
  {
    url: "/",
    label: "pc",
    img: "http://placeimg.com/242/242/animals",
    title: "title5",
    day: "2023.01 ~ 2023.02",
    skill: "Html, Scss, jQuery",
  },
];
